export const Ingredients = {
  liquors: [
    "151 Proof Rum",
    // Combine with "Anejo Rum"
    "Añejo Rum",
    "Absinthe",
    // Consider combining Absolute ingredients into generic "vodka"
    /* Absolut Citron included in:
        - 9 1/2 Weeks
        - Absolut Evergreen
        - Absolut Limousine
        - Absolut Summertime
        - Absolutly Screwed Up
        - Cosmopolitan
        - Lemon Shot
        - New York Lemonade
    */
    "Absolut Citron",
    /* Absolut Kuran included in:
        - 1-900-FUK-MEUP
        - Absolut Sex
        - Kurant Tea
    */
    "Absolut Kurant",
    /* Absolut Peppar included in:
        - Fahrenheit 5000
    */
    "Absolut Peppar",
    /* Absolut Vodka included in:
        - Absolut Stress #2
        - Absolutely Cranberry Smash
        - Arizona Stingers
        - AT&T
          - Name seems to reference Absolut Vodka, Tanqueray Gin, and Tonic
          - Common enough to care about inclusion?
        - Lemon Drop
          - Should not be Absolut specific
    */
    "Absolut Vodka",
    "Advocaat",
    "Apple Brandy",
    "Apricot Brandy",
    "Aquavit",
    "Bacardi Limon",
    "Blackberry Brandy",
    "Blackstrap Rum",
    "Blended Scotch",
    "Blended Whiskey",
    "Bourbon",
    "Brandy",
    "Cachaca",
    "Cherry Brandy",
    "Coconut Rum",
    "Coffee Brandy",
    "Cognac",
    "Corona",
    "Cranberry Vodka",
    "Crown Royal",
    "Dark Rum",
    "Everclear",
    "Firewater",
    "Gin",
    "Gold Rum",
    "Gold Tequila",
    "Grain Alcohol",
    "Irish Whiskey",
    "Islay Single Malt Scotch",
    "Jack Daniels",
    "Jim Beam",
    "Johnnie Walker",
    "Lemon Vodka",
    "Light Rum",
    "Lime Vodka",
    "Malibu Rum",
    "Mezcal",
    "Peach Vodka",
    "Peach Brandy",
    "Pisco",
    "Raspberry Vodka",
    "Rum",
    "Rye Whiskey",
    "Sake",
    "Scotch",
    "Shochu",
    "Sloe gin",
    "Soju",
    "Spiced rum",
    "Tennessee Whiskey",
    "Tequila",
    "Vanilla Vodka",
    "Vodka",
    "Whiskey",
    "Whisky",
    "White Rum",
    "Wild Turkey",
    "Zima",
  ],
  beers: [
    "Ale",
    "Beer",
    "Guinness Stout",
    "Lager",
  ],
  wines: [
    "Champagne",  
    "Dry Vermouth",
    "Port",
    "Prosecco",
    "Red wine",
    "Rose",
    "Rosso Vermouth",
    "Ruby Port",
    "Sherry",
    "Sweet Vermouth",
    "Vermouth",
    "White Wine",
    "Wine"
  ],
  liqueurs: [
    "Amaretto",
    "Amaro Montenegro",
    "Anisette",
    "Aperol",
    "Apfelkorn",
    "Apple Schnapps",
    "Baileys Irish Cream",
    "Banana Liqueur",
    "Benedictine",
    "Black Sambuca",
    "Blueberry Schnapps",
    "Blue Curacao",
    "Butterscotch Schnapps",
    "Campari",
    "Chambord Raspberry Liqueur",
    "Cherry Heering",
    "Cherry Liqueur",
    "Chocolate Liqueur",
    "Coconut Liqueur",
    "Cointreau",
    "Coffee Liqueur",
    "Creme de Banane",
    "Creme de Cacao",
    "Creme de Cassis",
    "Creme de Menthe",
    "Creme de Mure",
    "Curacao",
    "Dark Creme de Cacao",
    "Drambuie",
    "Dry Curacao",
    "Dubonnet Rouge",
    "Erin Cream",
    "Falernum",
    "Frangelico",
    "Galliano",
    "Grand Marnier",
    "Godiva Liqueur",
    "Goldschlager",
    "Green Chartreuse",
    "Green Creme de Menthe",
    "Hot Damn",
    "Hpnotiq",
    "Irish Cream",
    "Jägermeister",
    "Kahlua",
    "Kirschwasser",
    "Kiwi Liqueur",
    "Kummel",
    "Lillet Blanc",
    "Lillet",
    "Limoncello",
    "Maraschino Liqueur",
    "Maui",
    "Melon Liqueur",
    "Midori Melon Liqueur",
    "Orange Curacao",
    "Ouzo",
    "Passoa",
    "Peach Schnapps",
    "Peachtree Schnapps",
    "Peppermint Schnapps",
    "Pernod",
    "Pisang Ambon",
    "Raspberry Liqueur",
    "Ricard",
    "Rumple Minze",
    "Sambuca",
    "Southern Comfort",
    "St. Germain",
    "Strawberry Liqueur",
    "Strawberry Schnapps",
    "Tia Maria",
    "Triple Sec",
    "White Creme de Menthe",
    "Yellow Chartreuse",
    "Yukon Jack",
  ],
  mixers: [
    "7-Up",
    "Agave Syrup",
    "Allspice",
    "Almond Flavoring",
    "Almond",
    "Angelica Root",
    "Angostura Bitters",
    "Anis",
    "Apple Cider",
    "Apple Juice",
    "Apple",
    "Applejack",
    "Apricot Nectar",
    "Apricot",
    "Asafoetida",
    "Banana",
    "Basil",
    "Berries",
    "Bitter Lemon",
    "Bitters",
    "Black pepper",
    "Blackberries",
    "Blackcurrant Cordial",
    "Blackcurrant Squash",
    "Blood Orange",
    "Blueberries",
    "Brown sugar",
    "Butter",
    "Candy",
    "Cantaloupe",
    "Caramel Coloring",
    "Caramel Sauce",
    "Carbonated Soft Drink",
    "Carbonated Water",
    "Cardamom",
    "Carrot",
    "Cayenne Pepper",
    "Celery Salt",
    "Cherries",
    "Cherry Grenadine",
    "Cherry Juice",
    "Cherry",
    "Chocolate Sauce",
    "Chocolate Ice-Cream",
    "Chocolate milk",
    "Chocolate syrup",
    "Chocolate",
    "Cider",
    "Cinnamon",
    "Cloves",
    "Club Soda",
    "Coca-Cola",
    "Cocoa Powder",
    "Coconut Milk",
    "Coconut Syrup",
    "Coffee",
    "Condensed Milk",
    "Coriander",
    "Corn Syrup",
    "Cornstarch",
    "Cranberries",
    "Cranberry Juice",
    "Cream of Coconut",
    "Cream",
    "Cucumber",
    "Cumin Seed",
    "Daiquiri Mix",
    "Demerara Sugar",
    "Dr. Pepper",
    "Egg White",
    "Egg Yolk",
    "Egg",
    "Elderflower Cordial",
    "Espresso",
    "Fennel seeds",
    "Figs",
    "Food Coloring",
    "Fresca",
    "Grapefruit Juice",
    "Grenadine",
    "Fresh Lemon Juice",
    "Fresh Lime Juice",
    "Fruit Juice",
    "Fruit Punch",
    "Fruit",
    "Ginger Beer",
    "Ginger Syrup",
    "Ginger Ale",
    "Ginger",
    "Glycerine",
    "Grape Soda",
    "Grape Juice",
    "Grapefruit Juice",
    "Grapes",
    "Grenadine",
    "Guava Juice",
    "Half-and-Half",
    "Heavy Cream",
    "Honey Syrup",
    "Honey",
    "Hot Sauce",
    "Hot Chocolate",
    "Ice",
    "Iced Tea",
    "Jello",
    "Kiwi",
    "Kool-Aid",
    "Lavender",
    "Lemon Juice",
    "Lemon Peel",
    "Lemon",
    "Lemon-Lime Soda",
    "Lemonade",
    "Licorice Root",
    "Lime Juice",
    "Lime Juice Cordial",
    "Lime Peel",
    "Lime",
    "Limeade",
    "Light Cream",
    "Mango",
    "Maple syrup",
    "Maraschino Cherry",
    "Marjoram leaves",
    "Marshmallows",
    "Milk",
    "Mini-Snickers Bars",
    "Mint Syrup",
    "Mint",
    "Mountain Dew",
    "Nutmeg",
    "Olive Brine",
    "Olive",
    "Orange Bitters",
    "Orange Juice",
    "Orange Peel",
    "Orange Bitters",
    "Orange Spiral",
    "Orange",
    "Oreo Cookie",
    "Orgeat Syrup",
    "Papaya",
    "Passion Fruit Juice",
    "Passion Fruit Syrup",
    "Peach Bitters",
    "Peach Nectar",
    "Pepper",
    "Peppermint Extract",
    "Pepsi Cola",
    "Peychaud Bitters",
    "Pina Colada Mix",
    "Pineapple Juice",
    "Pineapple Syrup",
    "Pineapple",
    "Pink Lemonade",
    "Pomegranate Juice",
    "Powdered Sugar",
    "Raisins",
    "Raspberry Syrup",
    "Red Chili Flakes",
    "Root Beer",
    "Rosemary Syrup",
    "Rosemary",
    "Roses Sweetened Lime Juice",
    "Salt",
    "Salted Chocolate",
    "Sarsaparilla",
    "Schweppes Russchian",
    "Sherbet",
    "Simple Syrup",
    "Sirup of Roses",
    "Soda Water",
    "Sour Mix",
    "Soy Sauce",
    "Sprite",
    "Strawberries",
    "Sugar Syrup",
    "Sugar",
    "Surge",
    // merge with Sweet and Sour Mix
    "Sweet and Sour",
    "Sweet and Sour Mix",
    "Tabasco Sauce",
    "Tea",
    "Thyme",
    "Tomato Juice",
    "Tonic Water",
    "Tropicana",
    "Vanilla Ice-Cream",
    "Vanilla Extract",
    "Vanilla Syrup",
    "Vanilla",
    "Water",
    "Watermelon",
    "Whipped Cream",
    "Whipping Cream",
    "Worcestershire Sauce",
    "Wormwood",
    "Yoghurt",
  ]
};