export const Ingredients = {
  liquors: [
    "absinthe",
    "brandy",
    "bourbon",
    "cognac",
    "gin",
    "rum",
    "scotch",
    "shochu",
    "soju",
    "sake",
    "tequila",
    "vodka",
    "whiskey",
  ],
  liqueurs: [
    "amaretto",
    "baileys",
    "blue curacao",
    "chambord",
    "cointreau",
    "creme de banane",
    "creme de cacao",
    "creme de cassis",
    "creme de menthe",
    "drambuie",
    "dry curacao",
    "frangelico",
    "grand marnier",
    "irish cream",
    "kahlua",
    "limoncello",
    "midori",
    "peach schnapps",
    "sambuca",
    "triple sec",
  ],
  mixers: [
    "angostura bitters",
    "club soda",
    "coconut water",
    "cranberry juice",
    "grapefruit juice",
    "grenadine",
    "lemon juice",
    "lime juice",
    "orange juice",
    "pineapple juice",
    "simple syrup",
    "soda water",
    "sweet and sour mix",
    "tonic water",
    "tomato juice",
  ]
};